# configs/trainer/gda_energy.yaml
module: trainers.gda_energy_trainer
class: GDAEnergyTrainer
args:
  epochs: 500
  batch_size: 100
  log_interval: 10
  device: cuda:0
  save_dir: checkpoints/gda_energy
