# configs/trainer/noise_gdad.yaml
module: trainers.noise_informed_trainer
class: NoiseInformedTrainer
args:
  epochs: 500
  batch_size: 100
  log_interval: 10
  device: cuda:0
  save_dir: checkpoints/noise_gdad
