class: TrajectoryDataset
module: datasets.base
args:
  batch_time: 5
  expected_config:
    F_ext: 0.39
    T: 10.0
    alpha: -1.0
    beta: 1.0
    gamma: 0.1
    samples: 100
    sigma: 0.01
    timescale: 10

train_data_file: "{data_root}/chaotic_duffing_01_train_trajectories.pth"
val_data_file: "{data_root}/chaotic_duffing_01_test_trajectories.pth"
test_data_file: "{data_root}/chaotic_duffing_01_test_trajectories.pth"