class: TrajectoryDataset
module: datasets.base
args:
  batch_time: 5
  expected_config:
    T: 10.0
    g: 9.81
    gamma: 0.1
    l: 1.0
    m: 1.0
    samples: 100
    sigma: 0.05
    timescale: 10

train_data_file: "{data_root}/damped_pendulum_05_train_trajectories.pth"
val_data_file: "{data_root}/damped_pendulum_05_test_trajectories.pth"
test_data_file: "{data_root}/damped_pendulum_05_test_trajectories.pth"