class: TrajectoryDataset
module: datasets.base
args:
  batch_time: 5
  expected_config:
    L1: 1.0
    L2: 1.0
    T: 10.0
    m1: 1.0
    m2: 1.0
    samples: 100
    sigma: 0.1
    timescale: 10

train_data_file: "{data_root}/double_pendulum_train_trajectories.pth"
val_data_file: "{data_root}/double_pendulum_test_trajectories.pth"
test_data_file: "{data_root}/double_pendulum_test_trajectories.pth"