class: TrajectoryDataset
module: datasets.base
args:
  batch_time: 5
  expected_config:
    T: 10.0
    alpha: 1.0
    samples: 100
    sigma: 0.1
    timescale: 10
    q_lower: -0.1
    q_upper: 0.1

train_data_file: "{data_root}/henon_helies_train_trajectories.pth"
val_data_file: "{data_root}/henon_helies_test_trajectories.pth"
test_data_file: "{data_root}/henon_helies_test_trajectories.pth"