class: TrajectoryDataset
module: datasets.base
args:
  batch_time: 5
  expected_config:
    F_ext: 0.0
    T: 10.0
    alpha: -1.0
    beta: 1.0
    gamma: 0.3
    samples: 100
    sigma: 0.1
    timescale: 10

train_data_file: "{data_root}/unforced_duffing_train_trajectories.pth"
val_data_file: "{data_root}/unforced_duffing_test_trajectories.pth"
test_data_file: "{data_root}/unforced_duffing_test_trajectories.pth"