# configs/dataset/windy_pendulum.yaml
class: TrajectoryDataset
module: datasets.base
args:
  batch_time: 5
  # If you need generation params:
  expected_config:
      mass: 1.0
      gravity: 9.81
      length: 1.0
      friction: 0.1
      wind_res: 0.1
      wind_speed: 1.0
      T: 10.0
      timescale: 10
      samples: 100
      q_lower: -0.785398
      q_upper: 0.785398
      sigma: 0.01
  
train_data_file: "{data_root}/windy_pendulum_train_trajectories.pth"
val_data_file: "{data_root}/windy_pendulum_test_trajectories.pth"
test_data_file: "{data_root}/windy_pendulum_test_trajectories.pth"
