test_generator:
  class: DoublePendulumDataset
  module: datasets.double_pendulum
  params: &id001
    L1: 1.0
    L2: 1.0
    T: 10.0
    m1: 1.0
    m2: 1.0
    samples: 100
    sigma: 0.1
    timescale: 10
test_loader:
  class: TrajectoryDataset
  module: datasets.base
  args:
    batch_time: 5
    data_path: data/double_pendulum_test_trajectories.pth
    expected_config: *id001
train_generator:
  class: DoublePendulumDataset
  module: datasets.double_pendulum
  params: *id001
train_loader:
  class: TrajectoryDataset
  module: datasets.base
  args:
    batch_time: 5
    data_path: data/double_pendulum_train_trajectories.pth
    expected_config: *id001
