test_generator:
  class: DuffingDataset
  module: datasets.duffing
  params: &id001
    F_ext: 1.0
    T: 10.0
    alpha: 1.0
    beta: 1.0
    gamma: 0.2
    samples: 100
    sigma: 0.1
    timescale: 10
test_loader:
  class: TrajectoryDataset
  module: datasets.base
  args:
    batch_time: 5
    data_path: data/duffing_test_trajectories.pth
    expected_config: *id001
train_generator:
  class: DuffingDataset
  module: datasets.duffing
  params: *id001
train_loader:
  class: TrajectoryDataset
  module: datasets.base
  args:
    batch_time: 5
    data_path: data/duffing_train_trajectories.pth
    expected_config: *id001
