test_generator:
  class: ForcedSpringDataset
  module: datasets.forced_spring
  params: &id001
    T: 10.0
    gamma: 0.1
    omega: 1.0
    F0: 0.1
    k: 1.0
    m: 1.0
    samples: 100
    sigma: 0.1
    timescale: 10
test_loader:
  class: TrajectoryDataset
  module: datasets.base
  args:
    batch_time: 5
    data_path: data/forced_spring_test_trajectories.pth
    expected_config: *id001
train_generator:
  class: ForcedSpringDataset
  module: datasets.forced_spring
  params: *id001
train_loader:
  class: TrajectoryDataset
  module: datasets.base
  args:
    batch_time: 5
    data_path: data/forced_spring_train_trajectories.pth
    expected_config: *id001
